apiVersion: v1
kind: Template
metadata:
  name: cicd-pipeline
parameters:
  - name: STORE
    value: "store"
    required: true
  - name: STORE_BACKEND
    value: "store-backend"
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: cicd
    name: cicd
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          def storeBackend="${STORE_BACKEND}"
          def store="${STORE}"
          node("maven") {
            stage("Initialize") {
              sh "curl -O https://raw.githubusercontent.com/isss-apps/workshop/master/settings.xml"
              stash name: "settings.xml", includes:"settings.xml"
            }
            stage("Build Maven ${storeBackend}") {
              git url: "https://github.com/isss-apps/${storeBackend}.git", branch: "master"
              unstash name:"settings.xml"
              sh "mvn -s settings.xml clean package"
              stash name:"${storeBackend}-jar", includes:"target/${storeBackend}.jar"
            }
            stage("Build Maven ${store}") {
              git url: "https://github.com/isss-apps/${store}.git", branch: "master"
              unstash name:"settings.xml"
              sh "mvn -s settings.xml clean package"
              stash name:"${store}-jar", includes:"target/${store}.jar"
            }
          }
          node {
            stage("Build images") {
            input message: "Promote to STAGE?", ok: "Promote"
              parallel (
                "${storeBackend} image": {
                    unstash name:"${storeBackend}-jar"
                    sh "oc start-build ${storeBackend} --from-file=target/${storeBackend}.jar --follow"
                },
                "${store} image": {
                    unstash name:"${store}-jar"
                    sh "oc start-build ${store} --from-file=target/${store}.jar --follow"
                }
              )
            }
            stage("Verify deployment") {
              parallel (
                "${storeBackend} DC": {
                  openshiftVerifyDeployment deploymentConfig: storeBackend
                },
                "${store} DC": {
                  openshiftVerifyDeployment deploymentConfig: store
                }
              )
            }
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${STORE_BACKEND}
    labels:
      application: ${STORE_BACKEND}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${STORE_BACKEND}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift
      type: Source
    triggers: []
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${STORE_BACKEND}
    labels:
      application: ${STORE_BACKEND}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${STORE}
    labels:
      application: ${STORE}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${STORE}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift
      type: Source
    triggers: []
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${STORE}
    labels:
      application: ${STORE}
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      project: ${STORE_BACKEND}
    name: ${STORE_BACKEND}
  spec:
    replicas: 1
    selector:
      project: ${STORE_BACKEND}
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        labels:
          project: ${STORE_BACKEND}
      spec:
        containers:
        - env:
          - name: "JAVA_APP_DIR"
            value: "/deployments"
          image: ${STORE_BACKEND}
          imagePullPolicy: "Always"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
    - imageChangeParams:
        automatic: true
        containerNames:
        - "spring-boot"
        from:
          kind: "ImageStreamTag"
          name: "${STORE_BACKEND}:latest"
      type: "ImageChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      project: ${STORE}
    name: ${STORE}
  spec:
    replicas: 1
    selector:
      project: ${STORE}
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        labels:
          project: ${STORE}
      spec:
        containers:
        - env:
          - name: "JAVA_APP_DIR"
            value: "/deployments"
          - name: "SPRING_DATASOURCE_USERNAME"
            value: "student"
          - name: "SPRING_DATASOURCE_PASSWORD"
            value: "isss-secret"
          image: ${STORE}
          imagePullPolicy: "Always"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
    - imageChangeParams:
        automatic: true
        containerNames:
        - "spring-boot"
        from:
          kind: "ImageStreamTag"
          name: "${STORE}:latest"
      type: "ImageChange"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      project: ${STORE_BACKEND}
    name: ${STORE_BACKEND}
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: ${STORE_BACKEND}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      project: ${STORE}
    name: ${STORE}
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: ${STORE}
